### ISSUE TITLE
Join Promp configuration with the doc

### ISSUE THREAD

**Issue by Aarbel** [arkhamdev/hyperterm-monokai#4]
HI @arkhamdev ,
Could you give your whole Prompt configuration with it ?
![image](https://user-images.githubusercontent.com/25119847/32704623-8c0bb17a-c808-11e7-9198-b7478a864528.png)

Thanks a lot !

**Comment by spikiti** [comment]
Hi, I use [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) and that's an existing theme called **'ys'** which you can find [here](https://github.com/robbyrussell/oh-my-zsh/wiki/Themes)
